<!DOCTYPE html><html><head><meta name="generator" content="Hexo 3.9.0"><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="description" content="瞎bb的私密小天地，羞"><title>关于java异常 | 做正确的事</title><link rel="stylesheet" type="text/css" href="/css/normalize.css"><link rel="stylesheet" type="text/css" href="/css/highlight.css"><link rel="stylesheet" type="text/css" href="/css/noise.css"><link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css"><link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico"><link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato"></head><body><!-- gallery that comes before the header--><article class="wrapper"><div class="post-main"><div class="nav"><nav class="container"><a href="/" class="sidebar-nav-item active">Home</a><a href="/archives" class="sidebar-nav-item">Archives</a><a href="/about" class="sidebar-nav-item">About</a></nav><div class="container post-meta"><div class="post-time">2016-11-16</div></div></div><div class="container post-header"><h1>关于java异常</h1></div><div class="container post-content"><p>写代码的时候一直使用checkstyle和findbug，checkstyle和findbug可以帮助你写出标准规范的代码。特别是跟intellij插件结合之后，你的缩进、格式、甚至是异常控制都会被规范化。比如之前的项目中，对于异常的管理很不严格，大家都是所以的throw Exception和catch Exception。所以有一天我就抽时间将这些Exception都改成了具体的某个异常。   </p>
<p>但是我发现，有些地方catch Exception甚至是catch Throwable是很必要的。   </p>
<p>比如rabbitmq处理rpc返回的地方，如果发送的rpc请求在worker端发生异常，这个异常可能是任何异常，甚至可能是一个Error，所以rabbitmq这里其实会throw Throwable。当然，这里其实是spring amqp抛出的。但是在处理这类异常的时候，还是不应该让Throwable流到上层，因为客户端只需要知道这里出现异常应该怎么办，而不是关心整个异常链。所以应该这样：    </p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">	xxx</span><br><span class="line">&#125; <span class="keyword">catch</span> (Throwable t) &#123;</span><br><span class="line">	<span class="function">Throw new <span class="title">SomeRPCException</span><span class="params">(t, <span class="string">"blablabla"</span>)</span></span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>另外在试图从异常中恢复，特别是在多线程中，尝试因为抛出的异常终止或恢复线程，也需要catch Exception／Throwable。</p>
</div></div><div class="post-main post-comment"></div></article><link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css"><script src="//cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script><script src="//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js"></script><script>$(document).ready(function() {
    $(".fancybox").fancybox();
});
</script></body></html>